# Generated by Django 3.1.4 on 2021-01-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
